spring.application.name=rest-api

spring.datasource.url=jdbc:postgresql://localhost:5432/books
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.org.flywaydb=DEBUG


spring.jpa.open-in-view = false